name: Bot Runner
on:
  schedule:
    - cron: '0 4 * * *'   # 7:00 AM EAT
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  bot:
    name: Run Telegram Bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Keep workflow active
        run: |
          git pull origin main
          date > last_run.txt
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add last_run.txt
          git commit -m "Update last run timestamp"
          git push origin main
      - name: Run Bot
        env:
          PYTHONPATH: src
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_PHONE_NUMBER: ${{ secrets.TELEGRAM_PHONE_NUMBER }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          python src/main.py &
          sleep 86400  # Sleep for 24 hours
          kill $!
